# Pandas: Working with Works

This notebook is for use with the Melbourne Digital Musicology Workshops. It uses the Melbourne Rare Concert Programs dataset and focuses on one record type: **Works**.

Because the dataset contains several record types, not every field has a value in every row. Selecting Works first gives us a smaller, clearer table for learning how to inspect, filter, count, and sort data in Pandas.

## 1. Import Libraries

`requests` fetches the dataset from a URL, and `pandas` helps us work with it as a DataFrame.

In [1]:
import requests
import pandas as pd

## 2. Load the Melbourne Concert Programs Dataset

Each item in the JSON describes one extracted fact from a concert program. The `record_type` field tells us what kind of fact it is. A Work record may have `composer`, `title`, and `movement_or_selection`, while other record types use different fields.

`pd.json_normalize()` turns the list of dictionaries into a flat DataFrame. When a field does not apply to a record, Pandas represents the missing value as `NaN`.

In [2]:
url = 'https://raw.githubusercontent.com/RichardFreedman/Summer2026/e9e8a4a716f11d12a36a9c7db63c87503b1444aa/Melbourne_Rare_Concert/Structured%20Data/concert_program_items.json'
response = requests.get(url)
response.raise_for_status()
raw_data = response.json()
concerts = pd.json_normalize(raw_data)

concerts.head()

,record_type,filename,source_pdf,txt_source_file,manifest_contents,manifest_date,manifest_organization,page_number,source_text,review_flags,place,date_text,name,role,composer,title,movement_or_selection,part_or_instrument,associated_work
0,venue,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,3,"Town Hall, Melbourne",[],"Town Hall, Melbourne",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,venue,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,20,"TOWN HALL,\nMELBOURNE",[],"TOWN HALL, MELBOURNE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,date,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,3,"Wednesday Evening, Sixth November, 1889",[],NaN,"Wednesday Evening, Sixth November, 1889",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,date,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,20,"WEDNESDAY EVENING\n6TH NOVEMBER, 1889.",[],NaN,"WEDNESDAY EVENING 6TH NOVEMBER, 1889.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,organization,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,3,Metropolitan Liedertafel,[],NaN,NaN,Metropolitan Liedertafel,presenting organization,NaN,NaN,NaN,NaN,NaN

## 3. Select Only Work Records

A boolean condition creates a mask of `True` and `False` values. We use it to keep only rows where `record_type` is `work`.

This is useful here because fields such as `composer` and `title` are meaningful for Works but are often empty for other record types.

In [3]:
works = concerts[concerts['record_type'] == 'work'].copy()
works.head(10)

,record_type,filename,source_pdf,txt_source_file,manifest_contents,manifest_date,manifest_organization,page_number,source_text,review_flags,place,date_text,name,role,composer,title,movement_or_selection,part_or_instrument,associated_work
10,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,7,"Cantata ""Harald's Bridal Voyage""\nHeinrich Hof...",[],NaN,NaN,NaN,NaN,Heinrich Hofmann,Harald's Bridal Voyage,None,NaN,NaN
11,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,11,Pianoforte Solo: Concerto in E Flat Major Beet...,[],NaN,NaN,NaN,NaN,Beethoven,Concerto in E Flat Major,None,NaN,NaN
12,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,12,Serenade\n\n(TENOR SOLO Mr. W. Clarence Fraser),[Composer not given in the program.],NaN,NaN,NaN,NaN,None,Serenade,None,NaN,NaN
13,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,12,"Song\n\n""L'Estasi""\n\nMiss O'Shannessy",[Composer not given in the program.],NaN,NaN,NaN,NaN,None,L'Estasi,None,NaN,NaN
14,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,13,"Selections from ""La Damnation de Faust"" \nBer...",[],NaN,NaN,NaN,NaN,Berlioz,La Damnation de Faust,Rakocsky March,NaN,NaN
15,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,13,2.—Easter Hymn,[],NaN,NaN,NaN,NaN,Berlioz,La Damnation de Faust,Easter Hymn,NaN,NaN
16,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,13,3.—Danse des Sylphes,[],NaN,NaN,NaN,NaN,Berlioz,La Damnation de Faust,Danse des Sylphes,NaN,NaN
17,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,13,4.—Chorus of Soldiers and Students,[],NaN,NaN,NaN,NaN,Berlioz,La Damnation de Faust,Chorus of Soldiers and Students,NaN,NaN
18,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,14,"Song ""Bedouin Love Song"" Coombs",[],NaN,NaN,NaN,NaN,Coombs,Bedouin Love Song,None,NaN,NaN
19,work,UDC20260028-13.pdf,UDC20260028-13.pdf,extracted_texts/OLMOCR/UDC20260028-13.txt,Concert Programs,1889,Melbourne Liedertafel,14,"Part Song ""Farewell"" Zinkel",[],NaN,NaN,NaN,NaN,Zinkel,Farewell,None,NaN,NaN

### Keep the Most Useful Columns

A subset DataFrame contains only the columns we want to study.

In [4]:
work_columns = [
    'record_type',
    'manifest_organization',
    'manifest_date',
    'page_number',
    'composer',
    'title',
    'movement_or_selection'
]
works = works[work_columns]
works.head(10)

,record_type,manifest_organization,manifest_date,page_number,composer,title,movement_or_selection
10,work,Melbourne Liedertafel,1889,7,Heinrich Hofmann,Harald's Bridal Voyage,None
11,work,Melbourne Liedertafel,1889,11,Beethoven,Concerto in E Flat Major,None
12,work,Melbourne Liedertafel,1889,12,None,Serenade,None
13,work,Melbourne Liedertafel,1889,12,None,L'Estasi,None
14,work,Melbourne Liedertafel,1889,13,Berlioz,La Damnation de Faust,Rakocsky March
15,work,Melbourne Liedertafel,1889,13,Berlioz,La Damnation de Faust,Easter Hymn
16,work,Melbourne Liedertafel,1889,13,Berlioz,La Damnation de Faust,Danse des Sylphes
17,work,Melbourne Liedertafel,1889,13,Berlioz,La Damnation de Faust,Chorus of Soldiers and Students
18,work,Melbourne Liedertafel,1889,14,Coombs,Bedouin Love Song,None
19,work,Melbourne Liedertafel,1889,14,Zinkel,Farewell,None

### Reorder Columns

The order of columns in a DataFrame is controlled by the order of names in the list. Here we put the composer and title near the front because they are the main fields we want to study.

In [5]:
reordered_columns = [
    'composer',
    'title',
    'movement_or_selection',
    'manifest_organization',
    'manifest_date',
    'page_number',
    'record_type'
 ]

works = works[reordered_columns]
works.head(10)

,composer,title,movement_or_selection,manifest_organization,manifest_date,page_number,record_type
10,Heinrich Hofmann,Harald's Bridal Voyage,None,Melbourne Liedertafel,1889,7,work
11,Beethoven,Concerto in E Flat Major,None,Melbourne Liedertafel,1889,11,work
12,None,Serenade,None,Melbourne Liedertafel,1889,12,work
13,None,L'Estasi,None,Melbourne Liedertafel,1889,12,work
14,Berlioz,La Damnation de Faust,Rakocsky March,Melbourne Liedertafel,1889,13,work
15,Berlioz,La Damnation de Faust,Easter Hymn,Melbourne Liedertafel,1889,13,work
16,Berlioz,La Damnation de Faust,Danse des Sylphes,Melbourne Liedertafel,1889,13,work
17,Berlioz,La Damnation de Faust,Chorus of Soldiers and Students,Melbourne Liedertafel,1889,13,work
18,Coombs,Bedouin Love Song,None,Melbourne Liedertafel,1889,14,work
19,Zinkel,Farewell,None,Melbourne Liedertafel,1889,14,work

## 4. Inspect the Works DataFrame

These methods help us understand the size and structure of the table.

In [6]:
works.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2889 entries, 10 to 11209
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   composer               2772 non-null   object
 1   title                  2889 non-null   object
 2   movement_or_selection  465 non-null    object
 3   manifest_organization  2889 non-null   object
 4   manifest_date          2889 non-null   object
 5   page_number            2889 non-null   int64
 6   record_type            2889 non-null   object
dtypes: int64(1), object(6)
memory usage: 180.6+ KB

In [7]:
works.shape

(2889, 7)

In [8]:
works.columns

Index(['composer', 'title', 'movement_or_selection', 'manifest_organization',
       'manifest_date', 'page_number', 'record_type'],
      dtype='object')

### Count Missing Values

`isna()` identifies missing values. Adding `.sum()` counts them in each column. This is especially important when working with records that do not all have the same fields.

Finding missing values is a **data-cleaning step**. After identifying them, we might decide to leave them missing, fill them with a meaningful value, remove rows, or investigate the original source. The right choice depends on the field and the research question. We will not make those cleaning decisions in this notebook; they belong in a later step, after the initial analysis.

In [9]:
works.isna().sum()

composer                  117
title                       0
movement_or_selection    2424
manifest_organization       0
manifest_date               0
page_number                 0
record_type                 0
dtype: int64

## 5. Filter Works by Their Values

Use `.notna()` when you want only rows with a value in a particular field.

In [10]:
named_composer_works = works[works['composer'].notna()]
named_composer_works[['composer', 'title']]

                     composer                             title
10           Heinrich Hofmann            Harald's Bridal Voyage
11                  Beethoven          Concerto in E Flat Major
14                    Berlioz             La Damnation de Faust
15                    Berlioz             La Damnation de Faust
16                    Berlioz             La Damnation de Faust
...                       ...                               ...
11205                  Wagner                         Lohengrin
11206                  Wagner                         Lohengrin
11207               Beethoven  Thirty-two Variations in C Minor
11208                  Wagner                        Tannhäuser
11209  G. W. L. Marshall-Hall          Australian National Song

[2772 rows x 2 columns]

We can also look for a word in a title. `na=False` prevents missing titles from causing an error.

In [11]:
works_with_symphony = works[
    works['title'].str.contains('symphony', case=False, na=False)
]
works_with_symphony[['composer', 'title']].head(10)

                   composer                                       title
529          Antonin Dvorak           Symphony No. 8 in G major, Op. 88
821             F. Schubert         Symphony No. 8 b minor <Unfinished>
822               A. Dvorák               Symphony No. 8 G major Op. 88
834                M. Gould                           Symphony for Band
1273             R. Strauss                          Symphony for Winds
1275             P. Fauchet                          Symphony in B flat
1436             B. Britten                       Simple Symphony Op. 4
1756              A. Dvořák  Symphony No.9 e-minor from "The New World"
1807               E. Bloch                                    Symphony
1956  František Vaclav Miča                         Symphony in D Major

## 6. Count and Sort Values

`value_counts()` counts how often each value appears. By default, missing values are left out.

In [12]:
works['composer'].value_counts().head(15)

composer
J. Brahms          104
R. Schumann         87
W. A. Mozart        86
J. S. Bach          73
F. Schubert         72
F. Chopin           69
C. Debussy          55
L. v. Beethoven     55
H. Wolf             46
G. Verdi            35
G. Puccini          35
J. Haydn            31
F. Liszt            28
M. Ravel            26
R. Strauss          25
Name: count, dtype: int64

In [13]:
works['manifest_organization'].value_counts()

manifest_organization
Musashino Academia Musicae              1951
Melbourne Liedertafel                    568
Musical Society of Victoria              188
University of Michigan                    74
Pacific Contemporary Music Festival       25
Asian Youth Music Camp                    23
Royal Albert Hall                         17
Royal College of Music                     9
London Royal Choral Society                8
Obergammerau Canada Educator's Visit       7
London Symphony Orchestra                  7
Australian Youth Orchestra                 4
London Queens Hall Piano                   4
Madang Amateur Theatrical Society          2
Lausanne Music Festival                    1
Paris Académie de musique et danse         1
Name: count, dtype: int64

In [14]:
works['manifest_date'].value_counts().sort_index()

manifest_date
1889        52
1891        10
1892        31
1893        24
1894        30
1896       192
1897         2
1898        13
1899       106
1901        41
1902        60
1903        32
1905        14
1906        19
1907        22
1910         6
1915        12
1916        18
1919        18
1925         9
1928        39
1929        36
1930        24
1931        29
1933        19
1934        11
1936         3
1938-39      7
1939         5
1967-68    281
1968-69    180
1969-71      1
1970        29
1972-73    154
1973-74    204
1975-76    176
1976-77    140
1977-78    301
1978       512
1979        25
Unknown      2
Name: count, dtype: int64

To sort the most common composers alphabetically instead of by frequency, turn the counts into a Series and use `.sort_index()`.

In [15]:
composer_counts = works['composer'].value_counts()
composer_counts.sort_index().head(15)

composer
17th Century       1
A. Alabiev         1
A. Artunian        1
A. Berg            2
A. Boito           1
A. Borodin         1
A. Bruckner        1
A. Caldara         1
A. Catalani        1
A. Cellier         2
A. Constantini     1
A. Corelli         3
A. D'Ambrosio      1
A. Dvorak         11
A. Dvorák          3
Name: count, dtype: int64

## 7. A Simple Data-Cleaning Example

The counts above are useful even when the data is not perfect. A separate cleaning step can create new, more convenient values for analysis. Here we create a surname-first composer column. We will split each name at the first space, reverse the two parts, and join them with a comma. This simple example assumes the composer value has a first name followed by a last name.

In [25]:
# let's look at the _unique_ values for composers in order to understand the scope of names used
sorted(works['composer'].dropna().unique(), key=str.casefold)

['17th Century',
 'A. Alabiev',
 'A. Artunian',
 'A. Berg',
 'A. Boito',
 'A. Borodin',
 'A. Bruckner',
 'A. Caldara',
 'A. Catalani',
 'A. Cellier',
 'A. Constantini',
 'A. Corelli',
 "A. D'Ambrosio",
 'A. Dvorak',
 'A. Dvorák',
 'A. Dvořák',
 'A. E. Grimshaw',
 'A. F. Tenaglia',
 'A. Falconieri',
 'A. Gabrieli',
 'A. Glazounow',
 'A. Grazunov',
 'A. I. Khachaturian',
 'A. Ignoto',
 'A. Jolivet',
 'A. Karzev',
 'A. Lebediew',
 'A. Lotti',
 'A. M. Storch',
 'A. Messager',
 'A. N. Skriabin',
 'A. Plumpton',
 'A. Ponchielli',
 'A. Reed',
 'A. Roussel',
 'A. Scarlatti',
 'A. Schönberg',
 'A. Scriabin',
 'A. Skliabin',
 'A. Skriabbin',
 'A. Skriabin',
 'A. Thomas',
 'A. Vivaldi',
 'A.Berg',
 'A.Boïto',
 'A.Dvorak',
 'A.Dvořák',
 'A.Khachaturian',
 'A.Ledèdev',
 'A.Melicher',
 'A.Ponchielli',
 'A.Scarlatti',
 'A.Vivaldi',
 'A.Webern',
 'Abt',
 'ABT',
 'Adams',
 'Akio Yashiro',
 'Akira Ogura',
 'Akira Yuyama',
 'Alberto Zelman',
 'Alfred Hill',
 'Alfred Reed',
 'Allitsen',
 'AMBROISE THOMAS',
 'Ambroise Thomas',
 'Andrew Imbrie',
 'anonymous',
 'ANTON BRUCKNER',
 'Antonin Dvorak',
 'Antonio de Cabezon',
 'Antonio Vivaldi',
 'Antonín Dvořák',
 'Appalachian',
 'ARCANGELO CORELLI',
 'Arditi',
 'Arensky',
 'Armstrong Gibbs',
 'Arr. Min Hui-fen',
 'ARRANGED BY BREWER',
 'Asthoiz.',
 'ASTHOLZ',
 'Astholz',
 'Atsuki Sumi',
 'Attributed to John Fornsette, a Monk of Reading Abbey, Circa. 1240.',
 'August Siede',
 'B. Bartok',
 'B. Bartók',
 'B. Britten',
 'B. Harbach',
 'B. Marcello',
 'B. Martinu',
 'B. Smetana',
 'B. Verdi',
 'B.Bartok',
 'B.Smetana',
 'Bach',
 'Bach-Tausig',
 'Barat',
 'Bargiel',
 'Bayley',
 'BAYLEY',
 'Bechsnitt',
 'BECKER',
 'Beethoven',
 'BEETHOVEN',
 'Beethoven,',
 'Beethoven.',
 'Bellini',
 'Bemberg',
 'Benedict',
 'BENEDICT',
 'Benjamin Britten',
 'Berlioz',
 'Bernardo Feldman',
 'Bishop',
 'Bizet',
 'BIZET',
 'Bloch',
 'Blockley',
 'BLUMENTHAL',
 'Blumenthal',
 'Bobaudi',
 'Borodin',
 'Boschat',
 'Boyd',
 'Brahms',
 'Brambach',
 'Briccialdi',
 'Bridge',
 'BRIDGE',
 'Bruch',
 'Bréval',
 'Burt Goldstein',
 'Byong-kon Kim',
 'Béla Bartók',
 'C. Bottegari',
 'C. C. Menotti',
 'C. C. Saint-Saens',
 'C. Czerny',
 'C. Debussy',
 'C. Dougherty',
 'C. Festa',
 'C. Fink',
 'C. Franck',
 'C. Frank',
 'C. Gounod',
 'C. J. Brambach',
 'C. Janson',
 'C. Jos. Brambach',
 'C. Loewe',
 'C. M. v. Weber',
 'C. M. Weber',
 'C. M. Widor',
 'C. Monteverdi',
 'C. Orff',
 'C. Ph. Em. Bach',
 'C. Sainst-Saens',
 'C. Saint-Saens',
 'C. Saint-Saëns',
 'C. Steggall',
 'C. V. Stanford',
 'C. VILLIERS STANFORD',
 'C. Villiers Stanford',
 'C. Weber',
 'C.Debussy',
 'C.M. Widor',
 'C.M.v. Weber',
 'C.M.Weber',
 'Campbell Tipton',
 'Carl Bohm',
 'Carl Maria von Weber',
 'Carmichael',
 'Caspani',
 'Cecil Sharp',
 'Cesar Franck',
 'Ch. W. Gluck',
 'Chabrier',
 'CHADWICK',
 'Chaminate',
 'Charles Dickens',
 'Charles Spencer Chaplin',
 'Charpentier',
 'Cheng (arr.)',
 'Chopin',
 'CHOPIN',
 'Chopin.',
 'Chung-Gil Kim',
 'Ciro. Pinsuti',
 'Claude M. Haydon (of this city)',
 'CLAUDIO MONTEVERDE',
 'Claudio Monteverdi',
 'Clive Carey',
 'Cobb',
 'Coleridge Taylor',
 'Coleridge-Taylor',
 'COLERIDGE-TAYLOR',
 'CONSTANTINE FESTA',
 'Constantine Festa (1541)',
 'Coombs',
 'Costi.',
 'Couen',
 'Cowen',
 'César Cui',
 "d'Indy",
 'D. Buxtehude',
 'D. Cimarosa',
 'D. Haddad',
 'D. Kabalevsky',
 'D. Kabalewski',
 'D. Milhaud',
 'D. Pierne',
 'D. Popper',
 'D. Scarlatti',
 'D. Shostakovic',
 'D. Shostakovich',
 'D.Cimarosa',
 'D.Shostakovich',
 'Daniel Pinkham',
 'David',
 'David Ocker',
 'Davidoff',
 'De Rille',
 "De' Acqua",
 'Debussy',
 'DeLamarter',
 'Delibes',
 'DENZA',
 'Deorak',
 'Derek Healey',
 'Dietrich Buxtehude',
 'Dimitri Shostakovich',
 'Distin',
 'Dittersdorf',
 'Dmitri Smirnov',
 'Dohnanyi',
 'Doming Lam',
 'Donald Erb',
 'Donizetti',
 'DONIZETTI',
 'Doppler',
 'Dr. Bridge',
 'Dr. John H. Bee',
 'DR. TORRANCE',
 'Dragonetti',
 'Drdla',
 'Dudley Buck',
 'Dunkler',
 'Dussek',
 'Dvorak',
 'Dvorák',
 'E. A. McDowell',
 'E. Bloch',
 'E. Bozza',
 'E. Chausson',
 'E. d. Cavalieri',
 'E. German',
 'E. Grieg',
 'E. H. Grieg',
 'E. Hatch',
 'E. Lalo',
 'E. Miller.',
 'E. N. Hocking',
 'E. Reiche',
 'E. Scheffmann',
 'E. Wolf-Ferrari',
 'E. Ysaye',
 'E.Bozza',
 'E.Lalo',
 'Ed. Greig',
 'Edouard Lalo',
 'Edouard Schutt',
 'Eduard Greig',
 'Edvard Greig',
 'Edvard Grieg',
 'EDVARD GRIEG',
 'Edward German',
 'EDWARD GRIEG',
 'Eiler Jensen',
 'Elgar',
 'Emil Sjögren',
 'F Schubert',
 'F. Alfano',
 'F. B. Mendelssohn',
 'F. Bridge',
 'F. Cavalli',
 'F. Chopin',
 'F. Cilea',
 'F. Ciléa',
 'F. Couperin (Le Grand)',
 'F. David',
 'F. Durante',
 'F. Gasparini',
 'F. Hiller',
 'F. Liszt',
 'F. Liszt.',
 'F. Martin',
 'F. Mascagni',
 'F. Mendelssohn',
 'F. Poulenc',
 'F. Schubert',
 'F. Strauss',
 'F. Suppe',
 'F.Alfano',
 'F.Chopin',
 'F.J. Gossac',
 'F.J. Haydn',
 'F.Liszt',
 'F.Martin',
 'F.Mendelssohn',
 'F.Schubert',
 "Faure'",
 'Fauré',
 'Felicien David',
 'Felix Mendelssohn',
 'Felix Mendelssohn, Bartholdy.',
 'Felix Mendelssohn-Bartholdy',
 'FELIX MENDELSSOHN-BARTHOLDY',
 'FISCHER',
 'Fischer',
 'Florent Schmitt',
 'Folk item',
 'Folk item Arr. Zhao Chun-feng',
 'Francesco Rossi',
 'Francisco Correa de Arrauxo',
 'Frank Bridge',
 'Frank Campo',
 'Frank St. Leger',
 'František Vaclav Miča',
 'Franz Abt',
 'Franz Liszt',
 'FRANZ LISZT',
 'Franz Schubert',
 'Frederic Chopin',
 'Frederic Earp',
 'Frescobaldi',
 'Friedrich the Great',
 'G. B. Pergolesi',
 'G. Bantock',
 'G. Bizet',
 'G. Bossini',
 'G. Caccini',
 'G. Carissimi',
 'G. D. da Nola',
 'G. Donizetti',
 'G. Enesco',
 'G. F. Handel',
 'G. F. Handel, 1685-1759.',
 'G. F. Händel',
 'G. Faure',
 'G. Fauré',
 'G. Frescobaldi',
 'G. Gastoldi',
 'G. Gershwin',
 'G. Giordani',
 'G. Holst',
 'G. Händel',
 'G. Jacob',
 'G. Kleinsinger',
 'G. Litaize',
 'G. Mahler',
 'G. P. da Palestrina',
 'G. P. de Palestrina',
 'G. Paisiello',
 'G. Pergolesi',
 'G. Ph. Telemann',
 'G. Pierne',
 'G. Pierné',
 'G. Puccini',
 'G. Rossini',
 'G. Sarti',
 'G. Torelli',
 'G. Verdi',
 'G. W. L. Marshall-Hall',
 'G. W. L. Marshall-Hall.',
 'G.Bizet',
 'G.Donizetti',
 'G.Enesco',
 'G.F. Handel',
 'G.F. Händel',
 'G.F.Händel',
 'G.Faure',
 'G.Holst',
 'G.Mahler',
 'G.P. Telemann',
 'G.Rossini',
 'G.Verdi',
 'Gabriel-Marie',
 'Gans',
 'Gastaldon',
 'Gemba Fujita',
 'George Gershwin',
 'German Folk Song',
 'Giordani',
 'GIOVANNI B. PERGOLESE',
 'GIOVANNI BATTISTA BONONCINI',
 'GIUSEPPE GIORDANI',
 'GIUSEPPE VERDI',
 'Glasounov',
 'Glazounow',
 'Glinka',
 'Gluck',
 'Gluck-Saint Saens',
 'GOETZ',
 'Goring Thomas',
 'GORING THOMAS',
 'Gorring Thomas',
 'Gounod',
 'GOUNOD',
 'Graben-Hoffmann',
 'Grainger',
 'Gregory Korchmar',
 'Greig',
 'Grieg',
 'Grétry',
 'Guido Agostini',
 'Guillaume-Gabriel Nivers',
 'Guilmant',
 'GUNGL-ELSÄSSER',
 'Gustav Holst',
 'Gustave Baldamus',
 'H. Berlioz',
 'H. Distler',
 'H. Dutilleux',
 'H. E. D. Hammond',
 'H. Eccles',
 'H. Goetz.',
 'H. Goetz—1840-76',
 'H. Gorecki',
 'H. Hanson',
 'H. J. Koellreutter',
 'H. Pfitzner',
 'H. Purcell',
 'H. Schröter',
 'H. Tomasi',
 'H. Wolf',
 'H.Ades',
 'H.Eccles',
 'H.Tomasi',
 'H.Wolf',
 'Hamish MacCunn',
 'Hamish MacCunn.',
 'Hamma',
 'HAMMA',
 'HANDEL',
 'Handel',
 'Handel.',
 'Hartel',
 'HATTON',
 'Hatton',
 'Haydn',
 'HAYDN',
 'Healey Willan',
 'Heinrich Hofmann',
 'Heinrich Zollner',
 'Heinz Schroter',
 'Hennig',
 'Henning Nelms',
 'Henschel',
 'Henselt',
 'Hidekazu Yamashita',
 'HIKARU HAYASHI',
 'Hikaru Hayashi',
 'Hiroaki Kuwabara',
 'Hiroko Akabane',
 'Hiromi Ishii',
 'Hiroshi Hoshina',
 'Hiroyuki Fujikake',
 'Hisatada Odaka',
 'Hodyn.',
 'Hofmann',
 'Hook (1746-1827)',
 'Hope Temple',
 'Hopper',
 'Horsley',
 'Hubay',
 'Hullah',
 'Huntze',
 'Hyde',
 'Höcsler',
 'I. Albéniz',
 'I. Stravinski',
 'I. Stravinsky',
 'I.Stravinsky',
 'Ichijuro Koide',
 'Igor Stravinsky',
 'J. ALBERT MALLINSON',
 'J. B. Lully',
 'J. Barat',
 'J. Benedict',
 'J. Brahms',
 'J. Brahms.',
 'J. C. Bach',
 'J. Ch. Pepusch',
 'J. Ch. Petz',
 'J. Duke',
 'J. E. Schmöller',
 'J. E. Schmölzer',
 'J. F. Händel',
 'J. Haydn',
 'J. Hubeau',
 'J. Ibert',
 'J. Kapi-Kralik',
 'J. Kendall',
 'J. Kuhnau',
 'J. Langlais',
 'J. M. Defay',
 'J. M. Leclair',
 'J. Marx',
 'J. Massenet',
 'J. N. David',
 'J. N. Hummel',
 'J. Nepomuk David',
 'J. Pachelbel',
 'J. Peri',
 'J. Pezel',
 'J. S. Bach',
 'J. S. Bach.',
 'J. S. Tchaikovsky',
 'J. Sibelius',
 'J. Siede.',
 'J. Strauss',
 'J. Suk',
 'J. Woelfl',
 'J.B. Chance',
 'J.Brahms',
 'J.G. Walter',
 'J.Haydn',
 'J.Marx',
 'J.N. Hummel',
 'J.S. Bach',
 'J.S.Bach',
 'J.Sousa',
 'Jan Pieter Sweelinck',
 'Janacek',
 'Jasper B. Rooper',
 'Jensen',
 'Jeong-gil Kim',
 'Jerome Kern',
 'Jian Guang-yi & Wang Zhi-wei',
 'Jiri Pauer',
 'Joan Tower',
 'JOHANN SEBASTIAN BACH',
 'JOHANNES BRAHMS',
 'Johannes Brahms',
 'JOHANNES BRAHMS,',
 'Johannes Brahms.',
 'Johannis Cabanilles',
 'John Barnes Chance',
 'John Blow',
 'JOHN DOWLAND',
 'John Dowland (1597)',
 'John Sebastian Bach',
 'JOHN WILBYE',
 'John Wilbye (1598)',
 'Joji Yuasa',
 'Joseph Haydn',
 'JOSEPH KENDALL',
 'JUDE',
 'Julius Siede',
 'Junsuke Akashi',
 'K. Baranović',
 'K. Czerny',
 'K. J. Alford',
 'K. Slavicky',
 'K.Stamitz',
 'K.Yamada',
 'Karel Husa',
 'Karg Elert',
 'Kazunobu Nakajima',
 'Kazuto Miyazawa',
 'Kengyo Yatsuhashi',
 'KETTEN',
 'King Henry VIII.',
 'Kiyoshige Koyama',
 'Kjenulf',
 'Kjerulf',
 'Kjerulff',
 'Kok-Ichi Hattori',
 'Kosaku Yamada',
 'KOSCHAT',
 'Kreisler',
 'Kreutzer',
 'KUCKEN',
 'Kuhlau',
 'Kässmayer',
 'Kücken',
 'KückeN',
 'L. Bernstein',
 'L. Boccherini',
 'L. Cherubini',
 'L. Daquin',
 'L. de Rille',
 'L. Deliebes',
 'L. Janacek',
 'L. Janácek',
 'L. Janáček',
 'L. Krämer',
 'L. Rossi',
 'L. Spohr',
 'L. Thuille',
 'L. v. Beethoven',
 'L. V. Beethoven',
 'L. van Beethoven',
 'L. Vinci',
 'L.Bocchirini',
 'L.R. Kasilag',
 'L.v. Beethoven',
 'L.v.Beethoven',
 'Lachner',
 'Lalo',
 'Land-Elsässer',
 'Lassen',
 'Lawson Marks',
 'Lee Williams',
 'Leonard Bernstein',
 'Leonard de Lorenzo',
 'LEONARDO LEO',
 'Liszt',
 'Liza Lehmann',
 'Lockwood',
 'Lohr',
 'Louis Lavater',
 'Lucantoni',
 'Lucy Broadwood',
 'Ludwig van Beethoven',
 'Luigi Boccherini',
 'Luigi Zaninelli',
 'M. A. Balakirev',
 'M. Balakirev',
 'M. Bavel',
 'M. Bruch',
 'M. Enrico Bossi',
 'M. Glinka',
 'M. Gould',
 'M. Henri SAUGUET',
 'M. Ingeneri',
 'M. J. Ravel',
 'M. Marais',
 'M. Mussorgsky',
 'M. Mussorgsky (Ravel)',
 'M. Pordenon',
 'M. Ravel',
 'M. Reger',
 'M. W. Balfe',
 'M.Persico',
 'M.Ravel',
 'MacDowell',
 'MacFadgen',
 'Mana-Zucca',
 'Marcel Dupré',
 'Marcello—Bach',
 'Mari Ishida',
 'Marilyn Shrude',
 'Marschner',
 'Marshall Bialosky',
 'Marzials',
 'Mascheroni',
 'MASCHERONI',
 'Mascheroni.',
 'Massenet',
 'MAUDE VALERIE WHITE',
 'Maurice Durufle',
 'Maurice Ravel',
 'Max Bruch',
 'MAX BRUCH',
 'Max Bruch.',
 'Max Reger',
 'Mendelssohn',
 'MENDELSsohn',
 'MENDELSSOHN',
 'Meyer-Helmund',
 'Meyerbeer',
 'MEYERBEER',
 'MICHAEL PRAETORIUS',
 'Michael Praetorius (1571-1621)',
 'Michio Miyagi',
 'Minoru Miki',
 'Montbrun',
 'Moore',
 'Moszkowski',
 'Moussorgsky',
 'Mozart',
 'Mozart.',
 'Mulet',
 'MULLER',
 'Murray',
 'Möhrin',
 'MÖHRIN',
 'Müller',
 'N. A. Rimsky-Korsakov',
 'N. Bruhns',
 'N. Cavalli',
 'N. Dello Joio',
 'N. K. Medtner',
 'N. Paganini',
 'N. Rimsky-Korsakov',
 'N. Vaccai',
 'N. W. Gade',
 'N.Dello-Joio',
 'Naohiro Iwai',
 'Naomi Hangai',
 'Negro Spiritual',
 'Nelson',
 'Nevin',
 'Nicodé',
 'Nicolai',
 'Nicolaus Bruhns',
 'Nicole de Grigny',
 'NICOLO PORPORA',
 'Norman Dello-Joio',
 'O. di Lassa',
 'O. Fauré',
 'O. Messiaen',
 'O. Respighi',
 'O. Schoeck',
 'O.Respighi',
 'Old Folk Song',
 'Old Italian.',
 'ORLANDO LASSUS',
 'Orlando Lassus (1520-1594)',
 'Osamu Shoji',
 'OTTO',
 'P. A. Grainger',
 'P. Bonneau',
 'P. Creston',
 'P. Du Mage',
 'P. Dukas',
 'P. E. Fletcher',
 'P. Fauchet',
 'P. Fonghetti',
 'P. Hindemith',
 'P. I. Tchaikovsky',
 'P. I. Tschaikowsky',
 'P. Konjović',
 'P. Mascagni',
 'P. Maurice',
 'P. Pisari',
 'P. Tanner',
 'P. Tchaikovsky',
 'P. Telemann',
 'P. Tschaikovsky',
 'P. Tschaikowsky',
 'P. Warlock',
 'P.Creston',
 'P.Grainger',
 'P.Hindemith',
 'P.I. Tschaikowsky',
 'P.Tchaikovsky',
 'Paderewski',
 'Paganini',
 'Paganini—Liszt',
 'Parry',
 'Percy Fletcher',
 'Percy Grainger',
 'Percy Kahn',
 'Peter Sculthorpe',
 'Peter Terry',
 'Ph. Vitali',
 'Piatti',
 'Pierné',
 'Pinsuti',
 'PINSUTI',
 'Pinsuti.',
 'Plumpton',
 'Ponchielli',
 'Popper',
 'Proch',
 'Puccini',
 'Purcell',
 'R. Addinsel',
 'R. Hahn',
 'R. Leoncavallo',
 'R. Mennin',
 'R. Nixon',
 'R. R. Bennet',
 'R. R. Bennett',
 'R. Scheumann',
 'R. Schumann',
 'R. Seifert',
 'R. Strauss',
 'R. V. Williams',
 'R. Vaughan Williams',
 'R. Wagner',
 'R. Zandonai',
 'R.Cardillo',
 'R.G.Montbrun',
 'R.Jager',
 'R.Schumann',
 'R.Strauss',
 'R.Zandonai',
 'Rabinstein',
 'Rachmaninoff',
 'Randall Thompson',
 'Reichardt',
 'Rev. J. R. Dykes, M.A.',
 'Reynaldo Hahn',
 'Rheinberger',
 'Richard Rodgers',
 'RICHARD WAGNER',
 'Richard Wagner',
 'Rimsky-Korsakoff',
 'Rinkel',
 'Robert Jager',
 'Robert Linn',
 'ROBERT SCHWALM',
 'Roschat',
 'Rossi (c. 1686)',
 'ROSSINI',
 'Rossini',
 'Rubenstein',
 'Rubinstein',
 'Rubio',
 'S. Alschausky(arr. Hansen)',
 'S. Barber',
 'S. Donaudy',
 'S. Hristić',
 'S. Ikegami',
 'S. Iwakawa',
 'S. Noskowski',
 'S. Prokofieff',
 'S. Prokofiev',
 'S. Rachmaninoff',
 'S. Rachmaninov',
 'S. Rakhmaninov',
 'S. Rakmaninov',
 'S. V. Rakhmaninov',
 'S.Prokofieff',
 'S.Prokofiev',
 'S.Rakhmaninov',
 'Saburo Takada',
 'SAINT SAENS',
 'Saint Saens',
 'Saint-Saëns',
 'Scarlatti',
 'Schaeffer',
 'Schafer',
 'Schubert',
 'SCHUBERT',
 'Schubert-Liszt',
 'Schubert-Plumpton',
 'Schubert-Wilhelm',
 'Schubert.',
 'Schubert—Liszt',
 'SCHUMANN',
 'Schumann',
 'Schumann-Plumpton',
 'Schumann.',
 'Sculthorpe',
 'Seifert',
 'Sergeant',
 'Sergei Rakhmaninov',
 'SERVAIS',
 'SEYMOUR SMITH',
 'Sgambati',
 'Shinobu Kodagawa',
 'Shinobu Kotagawa',
 'Shui-Long Ma',
 'Sibelius',
 'Sigurd Lie',
 'Sinigaglia',
 'Sir Arthur Sullivan',
 'Sir E. Elgar',
 'SIR EDWARD ELGAR.',
 'Sir W. C. F. Robinson',
 'Sook-Ja Oh',
 'Spicker',
 'Spohr',
 'Stanford',
 'Stern',
 'Steven Stucky',
 'STORCH',
 'Stradella',
 'STRADELLA',
 'Strauss',
 'Strauss-Elsasser',
 'Stravinsky',
 'Sullivan',
 'Svendsen',
 'T. Albinoni',
 'T. F. Dunhill',
 'T. Mattei',
 'T. Mayuzumi',
 'T. Yamauchi',
 'Tadao Sawai',
 'Takashi Gunji',
 'Takashi Niikura',
 'Takeshi Niikura',
 'Tatsumi Suzuki',
 'Taubert',
 'Tchaikovsky',
 'Tchaikowsky',
 'THOMAS MORLEY',
 'Thomas Morley (1594)',
 'Thomas Morley (1595)',
 'Tippett',
 'Toru Kobayashi',
 'Toru Tamura',
 'Toshiko Nishiyama',
 'Toshimitsu Tanaka',
 'Toshiro Mayuzumi',
 'Tosti',
 'Tours',
 'Traditional',
 'Tschaikowsky',
 'Tschatkowski',
 'U. Giordano',
 'U.Giordano',
 'V. Bellini',
 'V. Billi',
 'V. Blazhevich',
 'V. Giannini',
 'V. Giordano',
 'V. Novak',
 'Various',
 'Vaughan Williams',
 'Vaughan-Williams',
 'Verdi',
 'VERDI',
 'Viktor Kalabis',
 'Viola Jager',
 'Vogrich',
 'Von Sturzman',
 'W. A. Mozart',
 'W. Benson',
 'W. Croft.',
 'W. E. NOTT',
 'W. E. Nott',
 'W. F. McBeth',
 'W. Francis Mcbeth',
 'W. Francis McBeth',
 'W. G. Whittaker',
 'W. J. Jude',
 'W. M. Rummel',
 'W. Piston',
 'W. Stockmeier',
 'W. Tschirch',
 'W. Wagner',
 'W. Walton',
 'W.A. Mozart',
 'W.A.Mozart',
 'W.Fortner',
 'Wagner',
 'Wagner-Liszt.',
 'Wagner—Liszt',
 'WAGNER—SCHUTT',
 'WATSON',
 'Weber',
 'Weber.',
 'Welsh air, arr. Greer',
 'Werner',
 'White',
 'Whitney-Kramer',
 'Wilhelm Kempff',
 'William Kraft',
 'Wing-fai Law',
 'Wolf-Ferrari',
 'Wolfgang Amadeus Mozart',
 'Woo-Sang Lim',
 'X. Montsalvatge',
 'Yong-jim Kim',
 'Yong-Jin Kim',
 'Yoshinao Nakada',
 'Yoshiro Irino',
 'Yurie Takahashi',
 'Yuzo Toyama',
 'Z. Kodaly',
 'Z. Kodály',
 'Zinkel',
 'Zollner.',
 'ベートーヴェン',
 'モーツァルト',
 'ヴォルフガング・アマデウス・モーツァルト',
 '中田 喜直 曲']

### Some Basic Cleaning Steps

Clearly we can notice many different problems:

- Inconsistent values:  `L. v. Beethoven`, `L. V. Beethoven`, `L. van Beethoven`, `Beethoven`, `BEETHOVEN`, and so on
- Different naming conventions:  `Wagner, Richard`, `Richard Wagner`
- Missing values
- Wrong data type is possible (such as a `string` or `integer` in the place of a `date`)

And others, too! This is a typical problem, and each situation will require a different solution.  Indeed, some collections will require several steps to get your data to be consistent and clean!

Here we create a simple function that will `split` and `reverse` the name of a composer, so that `Richard Wagner` becomes `Wagner, Richard`.

- The function accepts any `string` we pass to it and returns the split and reversed items.  

- We `apply` function to all rows of the dataframe at once, and put the results in a new column.

This will NOT solve all the problems in our composer column, but it is a start!

In [26]:
# create the function
def surname_first(composer):
    # a default value 'composer' if the field is empty
    if pd.isna(composer):
        return 'no composer given'
    # otherwise we split the name on the `space` between the names
    name_parts = composer.split(' ', 1)
    # and check the length of the result--if it's 2, then we return the two names separately, in reverse order
    if len(name_parts) == 2:
        return f'{name_parts[1]}, {name_parts[0]}'
    return composer


# finally we `apply` the function to the composer column, and return two new columns with the split names
works['composer_surname_first'] = works['composer'].apply(surname_first)
works[['composer', 'composer_surname_first']].drop_duplicates().head(50)

                  composer  composer_surname_first
10        Heinrich Hofmann       Hofmann, Heinrich
11               Beethoven               Beethoven
12                    None       no composer given
14                 Berlioz                 Berlioz
18                  Coombs                  Coombs
19                  Zinkel                  Zinkel
20                 Strauss                 Strauss
149         RICHARD WAGNER         WAGNER, RICHARD
151        JOHANNES BRAHMS        BRAHMS, JOHANNES
152            Franz Liszt            Liszt, Franz
153           EDWARD GRIEG           GRIEG, EDWARD
154            FRANZ LISZT            LISZT, FRANZ
348       Gustave Baldamus       Baldamus, Gustave
349            M. W. Balfe            W. Balfe, M.
350              Donizetti               Donizetti
351            W. Tschirch            Tschirch, W.
352                 Chopin                  Chopin
353           17th Century           Century, 17th
354              Franz Abt              Abt, Franz
355  Sir W. C. F. Robinson  W. C. F. Robinson, Sir
356                 Hartel                  Hartel
357            Mendelssohn             Mendelssohn
358                Bobaudi                 Bobaudi
359                Höcsler                 Höcsler
360                Pinsuti                 Pinsuti
361               De Rille               Rille, De
362                Dunkler                 Dunkler
363      Schubert-Plumpton       Schubert-Plumpton
364      Schumann-Plumpton       Schumann-Plumpton
499          Henning Nelms          Nelms, Henning
526       Benjamin Britten       Britten, Benjamin
527       Luigi Boccherini       Boccherini, Luigi
528       Peter Sculthorpe       Sculthorpe, Peter
529         Antonin Dvorak         Dvorak, Antonin
629           A. M. Storch           M. Storch, A.
630                 Arditi                  Arditi
633                 Rinkel                  Rinkel
820           W. A. Mozart           A. Mozart, W.
821            F. Schubert            Schubert, F.
822              A. Dvorák              Dvorák, A.
823        C. Ph. Em. Bach        Ph. Em. Bach, C.
824             J. S. Bach             S. Bach, J.
827               E. Grieg               Grieg, E.
829             L. Thuille             Thuille, L.
830           A. Glazounow           Glazounow, A.
831             R. Strauss             Strauss, R.
832              H. Hanson              Hanson, H.
833              H. Tomasi              Tomasi, H.
834               M. Gould               Gould, M.
835         P. A. Grainger         A. Grainger, P.

In [27]:
works.head()

,composer,title,movement_or_selection,manifest_organization,manifest_date,page_number,record_type,composer_surname_first
10,Heinrich Hofmann,Harald's Bridal Voyage,None,Melbourne Liedertafel,1889,7,work,"Hofmann, Heinrich"
11,Beethoven,Concerto in E Flat Major,None,Melbourne Liedertafel,1889,11,work,Beethoven
12,None,Serenade,None,Melbourne Liedertafel,1889,12,work,no composer given
13,None,L'Estasi,None,Melbourne Liedertafel,1889,12,work,no composer given
14,Berlioz,La Damnation de Faust,Rakocsky March,Melbourne Liedertafel,1889,13,work,Berlioz

## 8. Recap

In this notebook we:

- loaded JSON data into a Pandas DataFrame
- selected one record type with a boolean condition
- chose and reordered a useful subset of columns
- inspected the DataFrame with `head()`, `info()`, `shape`, and `columns`
- identified missing values with `isna().sum()` and discussed possible cleaning choices
- filtered rows with `.notna()` and `.str.contains()`
- counted and sorted values with `value_counts()` and `sort_index()`
- created a new surname-first composer column as a data-cleaning example

The main lesson is to understand which fields apply to the records you are analysing before counting, comparing, or cleaning their values.